-- AlterTable
ALTER TABLE `transferencias`
  MODIFY `origem` VARCHAR(100) NULL,
  MODIFY `destino` VARCHAR(100) NULL,
  MODIFY `tipo` ENUM('TRANSFERENCIA', 'ENTRADA', 'SAIDA') NOT NULL DEFAULT 'TRANSFERENCIA';
