const kFnmCategories = <String>[
  'Analgésicos',
  'Anti-inflamatórios',
  'Antimicrobianos',
  'Antiparasitários',
  'Antialérgicos',
  'Antigripais e Antitússicos',
  'Cardiovasculares',
  'Antidiabéticos',
  'Gastrointestinais',
  'Respiratórios',
  'Sistema Nervoso',
  'Vitaminas e Minerais',
  'Hormônios e Contraceptivos',
  'Dermatológicos',
  'Oftálmicos',
  'Otológicos',
  'Ginecológicos',
  'Urológicos',
  'Antissépticos e Desinfetantes',
  'Soluções e Reidratação',
  'Anestésicos',
  'Outros',
];

String fnmCategoryLabel(String nome) => nome.replaceAll('_', ' ');
