-- Adiciona módulos de dashboard dedicados ao enum SystemModule.
ALTER TABLE `role_permissions`
MODIFY `module` ENUM(
  'REQUISICOES',
  'COMPRAS',
  'PRODUTOS',
  'LOTES',
  'INVENTARIO',
  'FORNECEDORES',
  'CLIENTES',
  'POS',
  'RELATORIOS',
  'UTILIZADORES',
  'CONFIGURACOES',
  'PROFORMA_INVOICES',
  'DASHBOARD_FARMACIA',
  'DASHBOARD_CAIXA',
  'FATURAS',
  'CAIXA',
  'ESTOQUE',
  'PSICOTROPICOS',
  'AUDITORIA'
) NOT NULL;

ALTER TABLE `user_permissions`
MODIFY `module` ENUM(
  'REQUISICOES',
  'COMPRAS',
  'PRODUTOS',
  'LOTES',
  'INVENTARIO',
  'FORNECEDORES',
  'CLIENTES',
  'POS',
  'RELATORIOS',
  'UTILIZADORES',
  'CONFIGURACOES',
  'PROFORMA_INVOICES',
  'DASHBOARD_FARMACIA',
  'DASHBOARD_CAIXA',
  'FATURAS',
  'CAIXA',
  'ESTOQUE',
  'PSICOTROPICOS',
  'AUDITORIA'
) NOT NULL;
